
import { db } from '../src/db';
import * as schema from '../src/db/schema';
import nodemailer from 'nodemailer';

async function debugMail() {
    console.log('--- Debugging Mail Settings ---');

    // 1. Fetch Settings
    const result = await db.select().from(schema.mail_settings).limit(1);
    const config = result[0]?.data as any;

    if (!config) {
        console.error('❌ No mail settings found in database.');
        return;
    }

    console.log('✅ Settings found:');
    console.log(`   Host: ${config.host}`);
    console.log(`   Port: ${config.port}`);
    console.log(`   User: ${config.user}`);
    console.log(`   Secure: ${config.secure} (${typeof config.secure})`);
    console.log(`   Pass: ${config.pass ? '****' : '(empty)'}`);
    console.log(`   From: ${config.from}`);

    // 2. Validate Config
    if (!config.host || !config.user || !config.pass) {
        console.error('❌ Missing required fields (host, user, or pass).');
    }

    // 3. Try to Create Transport
    console.log('\n--- Testing Transporter Connection ---');
    const transporter = nodemailer.createTransport({
        host: config.host,
        port: parseInt(config.port || '587'),
        secure: config.secure === true || config.secure === 'true',
        auth: {
            user: config.user,
            pass: config.pass,
        },
        logger: true, // Enable built-in logger
        debug: true   // Enable debug output
    });

    try {
        console.log('Verifying transporter configuration...');
        await transporter.verify();
        console.log('✅ Transporter verification successful! Server is ready to take messages.');
    } catch (error: any) {
        console.error('❌ Transporter verification failed:');
        console.error(error.message);
        console.error(error);
        return;
    }

    // 4. Try Send
    console.log('\n--- Attempting to Send Test Email ---');
    try {
        const info = await transporter.sendMail({
            from: config.from || config.user,
            to: 'yusuffgur@gmail.com',
            subject: 'Debug Test Email via Script',
            html: '<p>This is a debug email generated by the debug-mail.ts script.</p>',
        });
        console.log('✅ Message sent:', info.messageId);
        console.log('Preview URL:', nodemailer.getTestMessageUrl(info));
    } catch (error: any) {
        console.error('❌ SendMail failed:');
        console.error(error.message);
    }
}

debugMail();
